apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-tuner
  namespace: hazelcast
spec:
  selector:
    matchLabels:
      app: sysctl-tuner
      component: system-tuning
      tier: node
  template:
    metadata:
      labels:
        app: sysctl-tuner
        component: system-tuning
        tier: node
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: hazelcast 
      hostPID: true
      hostNetwork: true
      containers:
        - name: sysctl-tuner
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:           # Mantido apenas este livenessProbe
            exec:
              command:
              - sh
              - -c
              - "sysctl net.core.rmem_max | grep 134217728"
            initialDelaySeconds: 30
            periodSeconds: 300
          image: ubuntu:22.04
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y procps
              
              # Configurações de rede básicas
              sysctl -w net.core.rmem_max=134217728
              sysctl -w net.core.wmem_max=134217728
              sysctl -w net.ipv4.tcp_rmem="4096 87380 134217728"
              sysctl -w net.ipv4.tcp_wmem="4096 87380 134217728"
              
              # Otimizações TCP básicas
              sysctl -w net.ipv4.tcp_max_syn_backlog=65536
              sysctl -w net.core.somaxconn=65536
              sysctl -w net.ipv4.tcp_timestamps=1
              sysctl -w net.ipv4.tcp_window_scaling=1
              
              # Otimizações TCP avançadas
              sysctl -w net.ipv4.tcp_keepalive_time=300
              sysctl -w net.ipv4.tcp_keepalive_intvl=60
              sysctl -w net.ipv4.tcp_keepalive_probes=10
              sysctl -w net.ipv4.tcp_fin_timeout=30
              sysctl -w net.ipv4.tcp_slow_start_after_idle=0
              sysctl -w net.ipv4.tcp_tw_reuse=1
              sysctl -w net.core.netdev_max_backlog=65536
              sysctl -w net.ipv4.tcp_max_tw_buckets=1440000
              sysctl -w net.ipv4.tcp_mtu_probing=1
              
              # Otimizações de memória
              sysctl -w vm.swappiness=1
              sysctl -w vm.max_map_count=262144
              sysctl -w vm.dirty_ratio=80
              sysctl -w vm.dirty_background_ratio=5
              sysctl -w vm.dirty_expire_centisecs=12000
              
              # Configurações de Huge Pages
              echo never > /sys/kernel/mm/transparent_hugepage/enabled
              echo never > /sys/kernel/mm/transparent_hugepage/defrag
              
              # Otimizações de file handles
              sysctl -w fs.file-max=1000000
              
              echo "Verificando configurações aplicadas:"
              sysctl net.core.rmem_max
              sysctl net.core.wmem_max
              sysctl net.ipv4.tcp_rmem
              sysctl net.ipv4.tcp_wmem
              sysctl net.ipv4.tcp_keepalive_time
              sysctl net.ipv4.tcp_keepalive_intvl
              sysctl net.ipv4.tcp_keepalive_probes
              sysctl net.core.netdev_max_backlog
              cat /sys/kernel/mm/transparent_hugepage/enabled
              sysctl vm.max_map_count
              sysctl fs.file-max

              # Mantém o container rodando
              while true; do sleep 3600; done
