apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-tuner
  namespace: hazelcast
spec:
  selector:
    matchLabels:
      name: sysctl-tuner
  template:
    metadata:
      labels:
        name: sysctl-tuner
    spec:
      nodeSelector:
        agentpool: hazelcast 
      hostPID: true
      hostNetwork: true
      containers:
        - name: sysctl-tuner
          image: ubuntu:22.04
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y procps
              # Configurações de rede
              sysctl -w net.core.rmem_max=134217728
              sysctl -w net.core.wmem_max=134217728
              sysctl -w net.ipv4.tcp_rmem="4096 87380 134217728"
              sysctl -w net.ipv4.tcp_wmem="4096 87380 134217728"
              
              # Otimizações TCP
              sysctl -w net.ipv4.tcp_max_syn_backlog=65536
              sysctl -w net.core.somaxconn=65536
              sysctl -w net.ipv4.tcp_timestamps=1
              sysctl -w net.ipv4.tcp_window_scaling=1
              
              # Otimizações de memória
              sysctl -w vm.swappiness=1
              sysctl -w vm.max_map_count=262144
              echo never > /sys/kernel/mm/transparent_hugepage/enabled
              echo never > /sys/kernel/mm/transparent_hugepage/defrag
              
              # Otimizações de file handles
              sysctl -w fs.file-max=1000000
              
              echo "Configurações aplicadas no node $(hostname):"
              sysctl net.core.rmem_max
              sysctl net.core.wmem_max
              sysctl net.ipv4.tcp_rmem
              sysctl net.ipv4.tcp_wmem
              cat /sys/kernel/mm/transparent_hugepage/enabled
              sysctl vm.max_map_count
              sysctl fs.file-max

              # Mantém o container rodando
              while true; do sleep 3600; done