# Configuração básica do cluster
cluster:
  memberCount: 2
  cluster-name: "axway-cluster"  # Nome do cluster adicionado aqui
  
image:
  tag: "5.3.8"  # Versão específica do IMDG
  repository: "hazelcast/hazelcast"

initContainers:
  - name: sysctl-tuner
    image: ubuntu:22.04
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
          - SYS_ADMIN
    command:
      - /bin/bash
      - -c
      - |
        apt-get update && apt-get install -y procps
        echo "Aplicando configurações de sysctl..."
        sysctl -w net.core.rmem_max=134217728
        sysctl -w net.core.wmem_max=134217728
        sysctl -w net.ipv4.tcp_rmem="4096 87380 134217728"
        sysctl -w net.ipv4.tcp_wmem="4096 87380 134217728"
        echo "Verificando configurações aplicadas:"
        sysctl net.core.rmem_max
        sysctl net.core.wmem_max
        sysctl net.ipv4.tcp_rmem
        sysctl net.ipv4.tcp_wmem

# Configurações do Hazelcast
hazelcast:
  yaml:
    hazelcast:
      cluster-name: "axway-cluster"
      serialization:
        use-native-byte-order: true
        allow-unsafe: true
        enable-compression: true
        enable-shared-object: true
        portable-version: 0
        
      network:
        join:
          kubernetes:
            enabled: true
            service-name: "${serviceName}"
            namespace: "${namespace}"
            kubernetes-master: "https://kubernetes.default.svc"
        port:
          auto-increment: true
          port-count: 100
          port: 5701
      #cp-subsystem:
      #  cp-member-count: 3  # Número mínimo recomendado
      #  group-size: 3       # Deve ser menor ou igual ao cp-member-count
      #  session-time-to-live-seconds: 300
      #  session-heartbeat-interval-seconds: 5
      #  missing-cp-member-auto-removal-seconds: 14400
      #  fail-on-indeterminate-operation-state: false
      map:
        "rate-limit*":
          eviction:
            eviction-policy: LRU
            max-size-policy: FREE_HEAP_PERCENTAGE  
            size: 15
          time-to-live-seconds: 1200
          max-idle-seconds: 600
          backup-count: 0
          async-backup-count: 0
          statistics-enabled: false
          per-entry-stats-enabled: false
          in-memory-format: BINARY
        default:
          backup-count: 1
          async-backup-count: 0
          eviction:
            eviction-policy: LRU
            max-size-policy: FREE_HEAP_PERCENTAGE
            size: 15
      properties:
        hazelcast.unsafe.mode: "true"
        hazelcast.performance.monitoring.enabled: "true"
        hazelcast.performance.monitoring.delay.seconds: "10"
        hazelcast.diagnostics.enabled: "false"
        hazelcast.diagnostics.directory: "/tmp/hazelcast/diagnostics"
        hazelcast.diagnostics.metric.level: "INFO"
        hazelcast.memory.free.min.percentage: "20"
        hazelcast.memory.free.max.percentage: "30"
        hazelcast.gc.check.period.seconds: "10"
        # Limitar proxies
        hazelcast.max.proxy.count: 1000
        hazelcast.proxy.count.check.interval: 60
        
        # Ajustar cache
        hazelcast.mc.cache.max.size: 512  # Reduzir de 2048
        # Memory Management
        hazelcast.max.heap.size.mb: "6144"

        # GC Settings
        hazelcast.gc.threshold.warning: "70"
        hazelcast.gc.threshold.error: "85"

        hazelcast.query.predicate.parallel.evaluation: "true"
        hazelcast.query.max.local.partition.limit.track.count: "100000"
        hazelcast.operation.call.timeout.millis: "60000"

        # Socket Buffer Sizes
        hazelcast.socket.receive.buffer.size: "65536"
        hazelcast.socket.send.buffer.size: "65536"
        # Network Thread Configs
        hazelcast.operation.thread.count: "2"
        hazelcast.io.thread.count: "2"
        hazelcast.operation.generic.thread.count: "2"

        hazelcast.backup.acks.enabled: "true"
        hazelcast.backup.timeout.millis: "5000"
        hazelcast.client.heartbeat.interval: "5000"
        hazelcast.client.heartbeat.timeout: "60000"
        hazelcast.client.max.no.heartbeat.seconds: "300"

        hazelcast.internal.map.expiration.cleanup.percentage: "100"
        hazelcast.internal.map.expiration.task.period.seconds: "1"
        hazelcast.map.eviction.batch.size: "250"
        hazelcast.map.eviction.cleanup.operation.count: "250"
        hazelcast.map.expiration.cleanup.operation.count: "200"
        hazelcast.map.invalidation.batch.size: "100"
        hazelcast.jmx: "false"
        hazelcast.logging.type: "slf4j"
        
        hazelcast.map.expiration.cleanup.threshold.percent: "25"
        hazelcast.map.invalidation.batch.enabled: "true"
        
        hazelcast.map.write.behind.queue.capacity: "2000"

        hazelcast.native.memory.allocator.type: "POOLED"
        hazelcast.native.memory.enabled: "true"
        hazelcast.operation.backup.timeout.millis: "60000"
        
        hazelcast.operation.responsequeue.idlestrategy: "backoff"
        
        hazelcast.partition.count: "271"
        hazelcast.phone.home.enabled: "false"
        hazelcast.socket.connect.timeout.seconds: "5"
        hazelcast.socket.keep.alive: "true"
        hazelcast.socket.no.delay: "true"
        hazelcast.wait.seconds.before.join: "5"

        hazelcast.native.memory.size.mb: "3072"  # 4GB
        hazelcast.native.memory.metadata.space.percentage: "20"
        hazelcast.backpressure.enabled: true
        hazelcast.backpressure.max.concurrent.invocations.per.partition: "100"

        # Otimizar operações do CP Subsystem
        hazelcast.cp.operation.thread.count: "2"
        hazelcast.cp.operation.timeout.millis: "10000"
        

  # Configurações de JVM
  javaOpts: >-
    -Xms6G
    -Xmx6G
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=50
    -XX:G1HeapRegionSize=4m
    -XX:+ParallelRefProcEnabled
    -XX:InitiatingHeapOccupancyPercent=45
    -XX:+UseStringDeduplication
    -XX:+UseNUMA
    -XX:+AlwaysPreTouch
    -XX:+ExplicitGCInvokesConcurrent 
    -XX:G1NewSizePercent=30
    -XX:G1MaxNewSizePercent=40
    -XX:MaxRAMPercentage=75
    -XX:MinRAMPercentage=50
    -XX:+UseCompressedOops
    -XX:+UseCompressedClassPointers


  # Métricas e monitoramento
  metrics:
    enabled: true
    service:
      type: ClusterIP
      port: 8080

  # Configurações de segurança
  securityContext:
    runAsUser: 65534
    fsGroup: 65534
    runAsNonRoot: true
# Recursos do container
resources:
  requests:
    memory: "6Gi"
    cpu: "4"
  limits:
    memory: "8Gi"
    cpu: "4"
  # Configurações de afinidade e anti-afinidade
nodeSelector:
  pool: utilities

tolerations:
- key: "workload"
  operator: "Equal"
  value: "utilities"
  effect: "NoSchedule"

# Configurações de persistência
persistence:
  enabled: true
  #storageClass: "default"  # Classe recomendada para produção
  accessModes:
    - ReadWriteOnce
  size: 20Gi
# Configuração do Management Center
mancenter:
  enabled: true
  image:
    repository: hazelcast/management-center
    tag: "5.3.4"  # Mesma versão do IMDG
  # Aumentar recursos
  requests:
    memory: "3Gi"  # Aumentado de 2Gi
    cpu: "1"
  limits:
    memory: "4Gi"  # Aumentado de 3Gi
    cpu: "2"
  # Configurar volume mounts no container principal
  volumeMounts:
    - name: mc-storage
      mountPath: /data
    - name: metrics-storage
      mountPath: /data/metrics
    - name: heap-dumps
      mountPath: /opt/hazelcast/mc/heap-dumps
  service:
    type: ClusterIP
    port: 8080
  persistence:
    enabled: false
    size: 20Gi  # Aumentado de 10Gi
    #storageClass: "managed-csi-premium"
    #storageClass: "default" 
    accessModes:
      - ReadWriteOnce
  # Configurar volume para heap dumps
  volumes:
    - name: mc-storage
      persistentVolumeClaim:
        claimName: hz-mc-storage
    - name: metrics-storage
      persistentVolumeClaim:
        claimName: hz-mc-metrics
    - name: heap-dumps
      emptyDir: {}


  # Configurar security context
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  
  javaOpts: >-
    -Xms2G 
    -Xmx3G
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/opt/hazelcast/mc/heap-dumps/
    -Dhazelcast.mc.max.client.response.size=20971520
    -Dhazelcast.mc.max.visible.instance.count=100
    -Dhazelcast.mc.max.client.message.size=20971520
    -Dhazelcast.mc.metrics.storage.retention.seconds=259200
    -Dhazelcast.mc.metrics.storage.frequency.seconds=30
    -Dhazelcast.mc.metrics.storage.write.batch.size=100
    -Dhazelcast.mc.rocksdb.metrics.storage.path=/data/metrics
    -Dhazelcast.mc.rocksdb.write.buffer.size=64
    -Dhazelcast.mc.rocksdb.max.write.buffer.number=4
    -Dhazelcast.mc.rocksdb.block.cache.size=512
    -Dspring.datasource.url=jdbc:h2:file:/data/hazelcast-mancenter;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MULTI_THREADED=TRUE
    -Dspring.jpa.properties.hibernate.jdbc.batch_size=50
    -Dspring.jpa.properties.hibernate.order_inserts=true
    -Dhazelcast.mc.healthCheck.enable=true
    -XX:NativeMemoryTracking=detail
  # Configurar liveness e readiness probes
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  licenseKey: ""
  security:
    enabled: true
    adminUser: "admin"
    adminPassword: "admin-pass-123"
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      #- hazelcast-mc.20230830.demo-latam.axway.com
      - hazelcast-mc.perfenv.apigw.axwaytest.net
  yaml:
    hazelcast-client:
      cluster-name: "axway-cluster"
      network:
        kubernetes:
          enabled: true
          namespace: "${namespace}"
          use-public-ip: false
